config/routes.rb
Wazup::Application.routes.draw do
  root :to => 'dashboard#index'
  resources :projects, only: [:create, :show]
  resources :checks, only: [:create]
end

app/models/check.rb
class Check
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :result, type: String

  embedded_in :host

  def state
    @state ||= begin
      if error_messages.blank?
        "passed"
      else
        "failed"
      end
    end
  end

  def error_messages
    @error_messages ||= begin
      verify
    end
  end

  private

  def verify
    Array.new.tap do |error_messages|
      JSON.parse(result).each do |result|
        result["elements"].each do |element|
          element["steps"].each do |step|
            if step["result"]["status"] == 'failed'
              error_messages << step["result"]["error_message"]
            end
          end
        end
      end
    end
  end

end

app/models/host.rb
class Host
  include Mongoid::Document
  field :name, type: String
  field :address, type: String
  field :auto, type: Boolean, default: false

  embedded_in :project
  embeds_many :checks

  def scripts
    project.scripts
  end

  def current_state
    checks.last.state if checks.present?
  end

  validates :address, presence: true
end

app/models/project.rb
class Project
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String

  embeds_many :hosts
  has_many :scripts

  def checks
    hosts.collect do |host|
      host.checks
    end.flatten
  end

  validates :title, presence: true
end

app/models/script.rb
class Script
  include Mongoid::Document
  field :title, type: String
  field :steps, type: String

  belongs_to :project

  validates :title, :steps, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/checks_controller.rb
require 'check_runner'

class ChecksController < ApplicationController
  def create
    project = Project.find(params[:project_id])
    host = project.hosts.find(params[:host_id])

    @check = CheckRunner.new(host).execute
    puts @check
    render :nothing
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @projects = Project.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def create
    @project = Project.new(params[:project])
    @project.save!

    respond_to do |format|
      format.html do
        redirect_to root_url, notice: "Success!"
      end
    end
  end

  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <h2>
        Projects 
        <%= link_to("#project-new-form", class: "btn btn-primary btn-xs", data: {toggle: "modal"}) do %>
          <span class="glyphicon glyphicon-plus"></span> Add
        <% end %>
      </h2>
      <div class="list-group projects-list">
        <% @projects.each do |project| %>
          <%= link_to project.title, project, class: 'list-group-item', remote: true %>
        <% end %>
      </div>
    </div>

    <div class="col-sm-9 project-area">
    </div>
  </div>
</div>

<!-- project form TODO move it to a partial -->
<div class="modal fade" id="project-new-form" tabindex="-1" role="dialog" aria-labelledby="newProjectLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for(Project.new) do |f| %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">New Project</h4>
        </div>
        <div class="modal-body">
            <%= f.text_field(:title, class: 'form-control', placeholder: 'Title') %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wazup</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_checks.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Date</th>
      <th>Host</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% checks.each do |check| %>
    <tr class="<%= check.state == "failed" ? "danger" : "" %>">
      <td><%= l check.created_at, format: :short %></td>
      <td><%= check.host.name %> - <%= check.host.address %></td>
      <td><%= check.state %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/_hosts.html.erb
<ul class="list-group">
  <% hosts.each do |host| %>
  <li class="list-group-item">
    <%= host.name %> - <%= host.address %>
    <% if host.auto %>
      <span class="label label-success">auto</span>
    <% end %>
    <%= link_to checks_url(host_id: host.id, project_id: host.project.id), remote: true, method: :post, class: 'btn btn-primary btn-xs' do %>
      <span class="glyphicon glyphicon-play"></span> Check it
    <% end %>
  </li>
  <% end %>
</ul>

app/views/projects/_scripts.html.erb
<ul class="list-group">
  <% scripts.each do |script| %>
  <li class="list-group-item">
    <%= script.title %>
  </li>
  <% end %>
</ul>

app/views/projects/show.html.erb
<h3><%= @project.title %></h3>
<ul class="nav nav-tabs" style="margin-bottom: 10px">
  <li class="active"><a href="#hosts" data-toggle="tab">Hosts</a></li>
  <li><a href="#check-history" data-toggle="tab">Check History</a></li>
  <li><a href="#scripts" data-toggle="tab">Scripts</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane" id="check-history">
    <%= render 'checks', checks: @project.checks %>
  </div>
  <div class="tab-pane active" id="hosts">
    <%= render 'hosts', hosts: @project.hosts %>
  </div>
  <div class="tab-pane" id="scripts">
    <%= render 'scripts', scripts: @project.scripts %>
  </div>
</div>

app/views/projects/show.js.erb
$(".project-area").html("<%= escape_javascript( render(template: 'projects/show.html.erb') ) %>");